import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import { currentProfile } from "@/lib/current-profile";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  const profile: any = await currentProfile();

  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body
          className={cn("relative h-screen flex flex-col w-full bg-background")}
        >
          {children}
          <Toaster />
          <div>{/* <ChatbotPage user={profile} /> */}</div>
        </body>
      </html>
    </ClerkProvider>
  );
}
